<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database with products from the frontend catalog.
     */
    public function run(): void
    {
        $products = $this->getProducts();

        foreach ($products as $data) {
            $colorsData = $data['colors'] ?? [];
            unset($data['colors']);
            unset($data['primary_color']);

            $product = Product::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );

            $colorIds = [];
            foreach ($colorsData as $colorVal) {
                $color = \App\Models\Color::firstOrCreate(
                    ['name' => $colorVal['name']],
                    ['hex' => $colorVal['hex']]
                );
                $colorIds[] = $color->id;
            }
            $product->colors()->sync($colorIds);
        }

        $this->command->info('Seeded ' . count($products) . ' products.');
    }

    /**
     * Return the full product catalog, mirrored from resources/js/data/products.ts.
     *
     * @return array<int, array<string, mixed>>
     */
    private function getProducts(): array
    {
        return [
            // ── New Arrivals ────────────────────────────────────────
            [
                'name'              => 'Aurora Pullover Hoodie – Ivory',
                'slug'              => Str::slug('Aurora Pullover Hoodie – Ivory'),
                'description'       => 'Designed for slow mornings and quiet afternoons. The kind of piece you reach for before you\'ve even thought about it.',
                'price'             => 295,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Ivory',
                'colors'            => [['name' => 'Ivory', 'hex' => '#F5F0E8', 'label' => 'Ivory']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/aurora-pullover-hoodie-ivory.webp'],
                'fabric_details'    => '70% Organic Cotton, 30% Mongolian Cashmere. Brushed interior for exceptional softness.',
                'care_instructions' => 'Hand wash cold or dry clean only. Lay flat to dry. Do not tumble dry.',
                'story'             => 'We spent eighteen months perfecting the weight of this fabric — heavy enough to feel luxurious, light enough to wear through September. The drop shoulder was calibrated seven times before we felt it right. This isn\'t a hoodie. It\'s a ritual.',
                'rating'            => 4.9,
                'review_count'      => 142,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 1,
            ],
            [
                'name'              => 'Slate Zip-Up Hoodie – Grey',
                'slug'              => Str::slug('Slate Zip-Up Hoodie – Grey'),
                'description'       => 'The one that started it all. Quiet confidence in the most comfortable form we know how to make.',
                'price'             => 245,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/slate-zip-up-hoodie-grey.webp'],
                'fabric_details'    => '100% Supima Cotton, 380gsm French terry. Pre-washed for immediate softness.',
                'care_instructions' => 'Machine wash cold, gentle cycle. Tumble dry low. Do not bleach.',
                'story'             => 'The Signature was our first design. We drew it once, got it right, and never touched the pattern again. Some things don\'t need improving — they just need to exist.',
                'rating'            => 4.8,
                'review_count'      => 89,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 2,
            ],
            [
                'name'              => 'Nova Zip-Up Hoodie – Light Blue',
                'slug'              => Str::slug('Nova Zip-Up Hoodie – Light Blue'),
                'description'       => 'A new season, a new silhouette. The cropped length was designed to work with everything — high-waisted trousers, wide-leg denim, weekend ease.',
                'price'             => 395,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Light Blue',
                'colors'            => [['name' => 'Light Blue', 'hex' => '#ADD8E6', 'label' => 'Light Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/nova-zip-up-hoodie-light-blue.webp'],
                'fabric_details'    => '80% Organic Cotton, 20% Recycled Polyester. Moisture-wicking lining.',
                'care_instructions' => 'Machine wash cold. Air dry. Do not iron directly on zipper.',
                'story'             => 'The quarter-zip arrived in our studio as a sketch on a coffee-stained napkin. Six months later, it was the piece every woman in our team couldn\'t stop wearing.',
                'rating'            => 4.7,
                'review_count'      => 67,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 3,
            ],
            [
                'name'              => 'Ember Zip-Up Hoodie – Dark Pink',
                'slug'              => Str::slug('Ember Zip-Up Hoodie – Dark Pink'),
                'description'       => 'Named for the two days we all look forward to most. Light, breathable, made for the hours between.',
                'price'             => 185,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Dark Pink',
                'colors'            => [['name' => 'Dark Pink', 'hex' => '#C24F6C', 'label' => 'Dark Pink']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/ember-zip-up-hoodie-dark-pink.avif'],
                'fabric_details'    => '100% Recycled Polyester Micro-fleece. Cloud-weight construction.',
                'care_instructions' => 'Machine wash cold. Tumble dry low. Do not iron.',
                'story'             => 'Saturday morning light through a kitchen window. Coffee. Nowhere to be. This is the piece we made for that exact moment.',
                'rating'            => 4.6,
                'review_count'      => 54,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 4,
            ],
            [
                'name'              => 'Atlas Pullover Hoodie – Taupe',
                'slug'              => Str::slug('Atlas Pullover Hoodie – Taupe'),
                'description'       => 'The ribbed hem is a small detail that changes everything. Structured where it counts, relaxed everywhere else.',
                'price'             => 265,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Taupe',
                'colors'            => [['name' => 'Taupe', 'hex' => '#8B8579', 'label' => 'Taupe']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/atlas-pullover-hoodie-taupe.webp'],
                'fabric_details'    => '65% Organic Cotton, 35% Modal. Ribbed cuffs and hem for shape retention.',
                'care_instructions' => 'Hand wash cold or machine wash gentle. Lay flat to dry.',
                'story'             => 'Modal was chosen for its natural sheen — a material that looks better worn than photographed, which is exactly what we wanted. The ribbing at hem and cuff is our signature touch: a little architecture in an otherwise effortless piece.',
                'rating'            => 4.8,
                'review_count'      => 76,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 5,
            ],
            [
                'name'              => 'Aspen Zip-Up Hoodie – Grey',
                'slug'              => Str::slug('Aspen Zip-Up Hoodie – Grey'),
                'description'       => 'An unexpected cut that has become our most talked-about new piece. The open back turns a hoodie into a statement.',
                'price'             => 225,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/aspen-zip-up-hoodie-grey.webp'],
                'fabric_details'    => '100% Pima Cotton, 320gsm. Open back panel with adjustable tie detail.',
                'care_instructions' => 'Hand wash cold. Lay flat to dry. Iron low if needed.',
                'story'             => 'The open-back design came from a conversation about how we dress when no one is watching — and then the revelation that sometimes the most beautiful thing is dressing for yourself. For long baths, Saturday mornings, quiet evenings in.',
                'rating'            => 4.7,
                'review_count'      => 48,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 6,
            ],
            [
                'name'              => 'Horizon Pullover Hoodie – Blue',
                'slug'              => Str::slug('Horizon Pullover Hoodie – Blue'),
                'description'       => 'The turtleneck met the hoodie and everything changed. Equal parts warmth and editorial.',
                'price'             => 275,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Blue',
                'colors'            => [['name' => 'Blue', 'hex' => '#4A90E2', 'label' => 'Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/horizon-pullover-hoodie-blue.avif'],
                'fabric_details'    => '75% Merino Wool, 25% Nylon. Slim turtleneck with deep hood.',
                'care_instructions' => 'Dry clean recommended. If hand washing, use cold water and wool detergent.',
                'story'             => 'We challenged ourselves: could a turtleneck and a hoodie coexist without compromise? Six prototypes later, we had the answer. The merino wool gives body while remaining impossibly light.',
                'rating'            => 4.9,
                'review_count'      => 93,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 7,
            ],
            [
                'name'              => 'Sierra Zip-Up Hoodie – Pink',
                'slug'              => Str::slug('Sierra Zip-Up Hoodie – Pink'),
                'description'       => 'Silk on the inside. The detail you\'ll discover on the first wear, and never forget.',
                'price'             => 215,
                'collection'        => 'new-arrivals',
                'primary_color'     => 'Pink',
                'colors'            => [['name' => 'Pink', 'hex' => '#F4A7B9', 'label' => 'Pink']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/New Arrivals/Sierra-zip-up-hoodie-pink.webp'],
                'fabric_details'    => 'Exterior: 100% Organic Cotton. Interior: 100% Habotai Silk lining.',
                'care_instructions' => 'Dry clean only. Store folded on a shelf.',
                'story'             => 'This was designed for the woman who knows the difference between what others see and what she feels. Silk against skin is a private luxury — something you carry with you through the day.',
                'rating'            => 4.9,
                'review_count'      => 38,
                'in_stock'          => true,
                'is_new'            => true,
                'is_best_seller'    => false,
                'featured'          => true,
                'active'            => true,
                'sort_order'        => 8,
            ],

            // ── Best Sellers ────────────────────────────────────────
            [
                'name'              => 'Dune Oversized Hoodie – Ivory',
                'slug'              => Str::slug('Dune Oversized Hoodie – Ivory'),
                'description'       => 'Our most-loved piece, season after season. There\'s a reason women come back for a second color.',
                'price'             => 235,
                'collection'        => 'best-sellers',
                'primary_color'     => 'Ivory',
                'colors'            => [['name' => 'Ivory', 'hex' => '#F5F0E8', 'label' => 'Ivory']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/Best Sellers/monarch-zip-up-hoodie-ivory.webp'],
                'fabric_details'    => '100% Supima Cotton, 400gsm. Garment-washed for immediate softness.',
                'care_instructions' => 'Machine wash cold, inside out. Tumble dry low.',
                'story'             => 'Three years running, the Classic has been our number-one piece. Not because it\'s trendy. Because it\'s right. Perfect drop shoulder. Perfect weight. Perfect hood. We\'ve had zero desire to change it.',
                'rating'            => 4.9,
                'review_count'      => 312,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => true,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 9,
            ],
            [
                'name'              => 'Summit Pullover Hoodie – Grey',
                'slug'              => Str::slug('Summit Pullover Hoodie – Grey'),
                'description'       => 'The deep kangaroo pocket wasn\'t an afterthought — it was the brief. Hands-free luxury for a hands-full life.',
                'price'             => 195,
                'collection'        => 'best-sellers',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/Best Sellers/summit-pullover-hoodie-grey.webp'],
                'fabric_details'    => '85% Organic Cotton, 15% Cashmere. Deep-set kangaroo pocket with reinforced seams.',
                'care_instructions' => 'Machine wash cold, gentle cycle. Air dry.',
                'story'             => 'Women have too many things to carry and not enough pockets. We solved exactly one of those problems — and made it beautiful in the process.',
                'rating'            => 4.8,
                'review_count'      => 258,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => true,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 10,
            ],
            [
                'name'              => 'Hunter Pullover Hoodie – Clove Green',
                'slug'              => Str::slug('Hunter Pullover Hoodie – Clove Green'),
                'description'       => 'Adjustable, adaptable, endlessly comfortable. The drawstring is crafted in the same fabric as the body — no plastic tips, no fraying.',
                'price'             => 210,
                'collection'        => 'best-sellers',
                'primary_color'     => 'Clove Green',
                'colors'            => [['name' => 'Clove Green', 'hex' => '#5C5C3D', 'label' => 'Clove Green']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/Best Sellers/hunter-pullover-hoodie-clove-green.webp'],
                'fabric_details'    => '100% Organic Cotton, 360gsm. Flat-knit drawstring in matching fabric.',
                'care_instructions' => 'Machine wash cold. Tumble dry low.',
                'story'             => 'We replaced the standard drawstring cord with a woven flat version in the same material as the body. A small change. The kind of detail that tells you someone was paying attention.',
                'rating'            => 4.8,
                'review_count'      => 204,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => true,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 11,
            ],
            [
                'name'              => 'Willow Pullover Hoodie – Brown',
                'slug'              => Str::slug('Willow Pullover Hoodie – Brown'),
                'description'       => 'The midi length hits at hip — long enough to be editorial, short enough to still be effortless.',
                'price'             => 275,
                'collection'        => 'best-sellers',
                'primary_color'     => 'Brown',
                'colors'            => [['name' => 'Brown', 'hex' => '#8C6A56', 'label' => 'Brown']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/Best Sellers/willow-pullover-hoodie-brown.webp'],
                'fabric_details'    => '90% Organic Cotton, 10% Elastane. Midi length, ribbed hem.',
                'care_instructions' => 'Machine wash cold, inside out. Air dry.',
                'story'             => 'Length is a conversation the fashion industry rarely has honestly. We made a piece that sits between the cropped and the longline — and found the exact spot where comfort and elegance agree.',
                'rating'            => 4.9,
                'review_count'      => 167,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => true,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 12,
            ],

            // ── Oversized ───────────────────────────────────────────
            [
                'name'              => 'Bone Oversized Hoodie – Ivory',
                'slug'              => Str::slug('Bone Oversized Hoodie – Ivory'),
                'description'       => 'Oversized as a philosophy, not just a size. Generous in every dimension, feather-light in every fiber.',
                'price'             => 265,
                'collection'        => 'oversized',
                'primary_color'     => 'Ivory',
                'colors'            => [['name' => 'Ivory', 'hex' => '#F5F0E8', 'label' => 'Ivory']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/bone-oversized-hoodie-ivory.png'],
                'fabric_details'    => '100% Long-Staple Cotton, 280gsm. Cloud-spun for exceptional lightness.',
                'care_instructions' => 'Machine wash cold. Air dry. Do not iron.',
                'story'             => 'We asked our customers what they wanted in an oversized piece — and every answer was the same: more of everything, but lighter. We made it feel like wearing nothing at all.',
                'rating'            => 4.9,
                'review_count'      => 134,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 13,
            ],
            [
                'name'              => 'Onyx Oversized Hoodie – Black',
                'slug'              => Str::slug('Onyx Oversized Hoodie – Black'),
                'description'       => 'The sleeve is the statement. Wide, fluid, and architectural — it moves differently than everything else in your wardrobe.',
                'price'             => 285,
                'collection'        => 'oversized',
                'primary_color'     => 'Black',
                'colors'            => [['name' => 'Black', 'hex' => '#1A1A1A', 'label' => 'Black']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/onyx-oversized-hoodie-black.avif'],
                'fabric_details'    => '85% Organic Cotton, 15% Silk. Extended wide sleeve, raw-edge finish.',
                'care_instructions' => 'Hand wash cold or dry clean. Lay flat to dry.',
                'story'             => 'When a sleeve is wide enough, it stops being a sleeve and starts being a gesture. This piece was designed around a single movement: reaching for something on a shelf and feeling the fabric fall beautifully.',
                'rating'            => 4.8,
                'review_count'      => 98,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 14,
            ],
            [
                'name'              => 'Rose Oversized Hoodie – Pink',
                'slug'              => Str::slug('Rose Oversized Hoodie – Pink'),
                'description'       => 'Wrap yourself in it completely. The cocoon silhouette was designed to make you feel held.',
                'price'             => 245,
                'collection'        => 'oversized',
                'primary_color'     => 'Pink',
                'colors'            => [['name' => 'Pink', 'hex' => '#F4A7B9', 'label' => 'Pink']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/rose-oversized-hoodie-pink.avif'],
                'fabric_details'    => '100% Organic Cotton, 420gsm. Extra-deep hood, cocooning body cut.',
                'care_instructions' => 'Machine wash cold, gentle. Tumble dry low.',
                'story'             => 'On grey days, this is the one. Heavy enough to feel substantial, shaped to wrap rather than hang. The cocoon cut doesn\'t show your form — it creates its own.',
                'rating'            => 4.8,
                'review_count'      => 112,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 15,
            ],
            [
                'name'              => 'Zephyr Oversized Hoodie – Sky Blue',
                'slug'              => Str::slug('Zephyr Oversized Hoodie – Sky Blue'),
                'description'       => 'Longline length, oversized body, unstructured hem. Wear it as a dress, over leggings, or layered. It decides for itself.',
                'price'             => 295,
                'collection'        => 'oversized',
                'primary_color'     => 'Sky Blue',
                'colors'            => [['name' => 'Sky Blue', 'hex' => '#87CEEB', 'label' => 'Sky Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/zephyr-oversized-hoodie-sky-blue.avif'],
                'fabric_details'    => '70% Organic Cotton, 30% Linen. Longline cut, unstructured hem, drop pockets.',
                'care_instructions' => 'Machine wash cold. Lay flat to dry. Do not tumble dry.',
                'story'             => 'Linen was the unexpected addition to the cotton. It gives the piece a slight drape and a coolness that makes it a three-season essential.',
                'rating'            => 4.9,
                'review_count'      => 87,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 16,
            ],
            [
                'name'              => 'Void Oversized Hoodie – Black',
                'slug'              => Str::slug('Void Oversized Hoodie – Black'),
                'description'       => 'Maximum shoulder drop, maximum comfort. Styled with tailored trousers, it becomes something else entirely.',
                'price'             => 240,
                'collection'        => 'oversized',
                'primary_color'     => 'Black',
                'colors'            => [['name' => 'Black', 'hex' => '#1A1A1A', 'label' => 'Black']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/void-oversized-hoodie-black.png'],
                'fabric_details'    => '100% Supima Cotton, 380gsm. Extended drop shoulder, oversized body.',
                'care_instructions' => 'Machine wash cold, inside out. Tumble dry low.',
                'story'             => 'The drop shoulder was measured to fall exactly at the middle of the upper arm. Not by accident — by calculation. It creates a silhouette that photographs incredibly well but, more importantly, moves beautifully.',
                'rating'            => 4.7,
                'review_count'      => 119,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 17,
            ],
            [
                'name'              => 'Ash Oversized Hoodie – Grey',
                'slug'              => Str::slug('Ash Oversized Hoodie – Grey'),
                'description'       => 'Named for exactly what it feels like. Substantial enough to replace a throw, wearable enough to replace a coat.',
                'price'             => 315,
                'collection'        => 'oversized',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/ash-oversized-hoodie-grey.png'],
                'fabric_details'    => '100% Organic Cotton, 500gsm heavyweight. Double-lined hood.',
                'care_instructions' => 'Machine wash cold. Air dry (may take extended time due to weight).',
                'story'             => 'Some pieces are designed for specific temperatures. This one was designed for the three months when you cannot decide if it\'s cold enough for a coat.',
                'rating'            => 4.9,
                'review_count'      => 76,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 18,
            ],
            [
                'name'              => 'Marine Oversized Hoodie – Blue',
                'slug'              => Str::slug('Marine Oversized Hoodie – Blue'),
                'description'       => 'Oversized but intentional. Interior seam work gives this piece structure that others in this category lack.',
                'price'             => 275,
                'collection'        => 'oversized',
                'primary_color'     => 'Blue',
                'colors'            => [['name' => 'Blue', 'hex' => '#4A90E2', 'label' => 'Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/oversized/marine-oversized-hoodie-blue.png'],
                'fabric_details'    => '100% Organic Cotton, 380gsm. Interior seam tape for shape retention.',
                'care_instructions' => 'Machine wash cold, gentle. Lay flat to dry.',
                'story'             => 'Oversized pieces can lose their shape. We used interior taping at key seams to ensure this one doesn\'t — even after years of washing. The structure is invisible but you\'ll feel the difference.',
                'rating'            => 4.8,
                'review_count'      => 91,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 19,
            ],

            // ── Everyday Essentials ─────────────────────────────────
            [
                'name'              => 'Haven Pullover Hoodie – Grey',
                'slug'              => Str::slug('Haven Pullover Hoodie – Grey'),
                'description'       => 'Before the day starts and after it ends. The piece that makes every ordinary moment feel considered.',
                'price'             => 185,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/haven-pullover-hoodie-grey.png'],
                'fabric_details'    => '100% Organic Cotton, 320gsm. Soft brushed interior.',
                'care_instructions' => 'Machine wash cold. Tumble dry low.',
                'story'             => 'We designed this piece for the space between sleep and the world. Soft enough to pull on before coffee, structured enough to wear to the corner shop. The ritual piece.',
                'rating'            => 4.7,
                'review_count'      => 198,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 20,
            ],
            [
                'name'              => 'Nomad Zip-Up Hoodie – Taupe',
                'slug'              => Str::slug('Nomad Zip-Up Hoodie – Taupe'),
                'description'       => 'Ready for the train, the meeting, the school run, and every hour between. Designed for real life at its most demanding.',
                'price'             => 215,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Taupe',
                'colors'            => [['name' => 'Taupe', 'hex' => '#8B8579', 'label' => 'Taupe']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/nomad-zip-up-hoodie-taupe.png'],
                'fabric_details'    => '80% Organic Cotton, 20% Nylon. Wrinkle-resistant finish, hidden zip pocket.',
                'care_instructions' => 'Machine wash cold. Tumble dry low.',
                'story'             => 'The Commuter was designed by walking a full working day. Platform to office to café to school. It needed to do all of it. It does.',
                'rating'            => 4.8,
                'review_count'      => 156,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 21,
            ],
            [
                'name'              => 'Echo Pullover Hoodie – Ivory',
                'slug'              => Str::slug('Echo Pullover Hoodie – Ivory'),
                'description'       => 'A slimmer fit for those who prefer their comfort without the volume. All the same quality, a more fitted silhouette.',
                'price'             => 195,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Ivory',
                'colors'            => [['name' => 'Ivory', 'hex' => '#F5F0E8', 'label' => 'Ivory']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/echo-pullover-hoodie-ivory.png'],
                'fabric_details'    => '100% Organic Cotton, 340gsm. Slim fit, tapered sleeves.',
                'care_instructions' => 'Machine wash cold. Tumble dry low.',
                'story'             => 'Some women want the volume. Some don\'t. The Everyday Slim was made for the latter — every quality decision made with a closer fit in mind.',
                'rating'            => 4.7,
                'review_count'      => 132,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 22,
            ],
            [
                'name'              => 'Roam Pullover Hoodie – Brown',
                'slug'              => Str::slug('Roam Pullover Hoodie – Brown'),
                'description'       => 'The farmers market, the pharmacy, the dog walk. Unstoppable in the mundane and beautiful in every setting.',
                'price'             => 175,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Brown',
                'colors'            => [['name' => 'Brown', 'hex' => '#8C6A56', 'label' => 'Brown']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/roam-pullover-hoodie-brown.png'],
                'fabric_details'    => '100% Organic Cotton, 300gsm. Medium-weight for versatility.',
                'care_instructions' => 'Machine wash warm. Tumble dry medium.',
                'story'             => 'The least glamorous brief in our history — design a hoodie for everything that needs to get done. And what we found was that the right piece makes even errands feel like an event.',
                'rating'            => 4.6,
                'review_count'      => 178,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 23,
            ],
            [
                'name'              => 'Layer Pullover Hoodie – Sky Blue',
                'slug'              => Str::slug('Layer Pullover Hoodie – Sky Blue'),
                'description'       => 'Made to be worn under, over, or between. Lightweight enough for three seasons of layering.',
                'price'             => 165,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Sky Blue',
                'colors'            => [['name' => 'Sky Blue', 'hex' => '#87CEEB', 'label' => 'Sky Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/layer-pullover-hoodie-sky-blue.png'],
                'fabric_details'    => '100% Organic Cotton, 240gsm. Ultra-lightweight for layering versatility.',
                'care_instructions' => 'Machine wash cold. Tumble dry low.',
                'story'             => 'The lightest piece we\'ve ever made. The Layering Essential was designed with one purpose: to disappear under a coat or anchor an outfit as a base. At 240gsm, it succeeds at both.',
                'rating'            => 4.7,
                'review_count'      => 214,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 24,
            ],
            [
                'name'              => 'Lounge Pullover Hoodie – Pink',
                'slug'              => Str::slug('Lounge Pullover Hoodie – Pink'),
                'description'       => 'For every evening at home that deserves a little more than ordinary. Softer than anything you\'ve worn while watching television.',
                'price'             => 205,
                'collection'        => 'everyday-essentials',
                'primary_color'     => 'Pink',
                'colors'            => [['name' => 'Pink', 'hex' => '#F4A7B9', 'label' => 'Pink']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/everyday-essentials/lounge-pullover-hoodie-pink.png'],
                'fabric_details'    => '80% Organic Cotton, 20% Bamboo. Ultra-soft brushed interior.',
                'care_instructions' => 'Machine wash cold, gentle. Air dry.',
                'story'             => 'Home is a place that deserves beautiful things. The bamboo blend gives a silkier hand feel than any standard cotton — it\'s the piece you\'ll want to put on the second you walk through the door.',
                'rating'            => 4.8,
                'review_count'      => 167,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 25,
            ],

            // ── Limited Edition ─────────────────────────────────────
            [
                'name'              => 'Obsidian Long Sleeve – Black',
                'slug'              => Str::slug('Obsidian Long Sleeve – Black'),
                'description'       => 'From our first-ever collection. Reproduced once — exactly as it was. Numbered.',
                'price'             => 495,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Black',
                'colors'            => [['name' => 'Black', 'hex' => '#1A1A1A', 'label' => 'Black']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/obsidian-long-sleeve-black.webp'],
                'fabric_details'    => '100% Extra-Fine Merino Wool. Numbered edition plate at inner hem.',
                'care_instructions' => 'Dry clean only. Store in the cotton bag provided.',
                'story'             => 'In our first year, we made forty units of a pullover that sold out in six hours. Three years of requests later, we agreed to make it again — once more, in a limited run. Each piece carries a handwritten number at the inner hem.',
                'rating'            => 5.0,
                'review_count'      => 24,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 26,
            ],
            [
                'name'              => 'Celestial Edition Hoodie – Sky Blue',
                'slug'              => Str::slug('Celestial Edition Hoodie – Sky Blue'),
                'description'       => 'Made to be worn at the hour when the rest of the world is quiet. Designed entirely in darkness.',
                'price'             => 395,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Sky Blue',
                'colors'            => [['name' => 'Sky Blue', 'hex' => '#87CEEB', 'label' => 'Sky Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/celestial-edition-hoodie-sky-blue.png'],
                'fabric_details'    => '100% Supima Cotton, 420gsm. Deep matte-black finish with tonal graphite stitching.',
                'care_instructions' => 'Machine wash cold, inside out. Tumble dry low. Do not bleach.',
                'story'             => 'Our creative director sketched this piece at 2am. She says that\'s the only hour when decisions are made without self-editing. We have no reason to doubt her.',
                'rating'            => 4.9,
                'review_count'      => 29,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 27,
            ],
            [
                'name'              => 'Forge Long Sleeve – Grey',
                'slug'              => Str::slug('Forge Long Sleeve – Grey'),
                'description'       => 'Co-designed with artist Elena Voss. The seam work is her signature — a language of lines written in fabric.',
                'price'             => 375,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Grey',
                'colors'            => [['name' => 'Grey', 'hex' => '#8E8E93', 'label' => 'Grey']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/forge-long-sleeve-grey.webp'],
                'fabric_details'    => '100% Supima Cotton, 400gsm. Artist signature seam detail at shoulder and chest.',
                'care_instructions' => 'Machine wash cold, inside out. Air dry.',
                'story'             => 'Elena works in materials — fabric, stone, paper. We asked her to approach a hoodie the way she approaches a sculpture: from the inside out. The visible seam lines are her answer. Wearable art.',
                'rating'            => 4.9,
                'review_count'      => 31,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 28,
            ],
            [
                'name'              => 'Blush Edition Hoodie – Pink',
                'slug'              => Str::slug('Blush Edition Hoodie – Pink'),
                'description'       => 'Cotton body, velvet trim. The textures coexist in a conversation we find endlessly interesting.',
                'price'             => 425,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Pink',
                'colors'            => [['name' => 'Pink', 'hex' => '#F4A7B9', 'label' => 'Pink']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/blush-edition-hoodie-pink.png'],
                'fabric_details'    => 'Body: 100% Organic Cotton. Trim: 100% Silk Velvet at cuffs, hood edge, and pocket entry.',
                'care_instructions' => 'Dry clean only. Do not expose velvet trim to water.',
                'story'             => 'Velvet on a hoodie should not work. We did it anyway because the textural contrast of matte cotton against crushed silk velvet is exactly the kind of contradiction that makes fashion interesting.',
                'rating'            => 4.8,
                'review_count'      => 22,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 29,
            ],
            [
                'name'              => 'Crest Long Sleeve – Ivory',
                'slug'              => Str::slug('Crest Long Sleeve – Ivory'),
                'description'       => 'Tonal hand-embroidery of native botanicals, placed by a craftsperson in our atelier in Lyon.',
                'price'             => 465,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Ivory',
                'colors'            => [['name' => 'Ivory', 'hex' => '#F5F0E8', 'label' => 'Ivory']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/crest-long-sleeve-ivory.webp'],
                'fabric_details'    => '100% Organic Cotton, 380gsm. Tonal silk thread embroidery. Each piece takes four hours to complete.',
                'care_instructions' => 'Dry clean only. Do not machine wash.',
                'story'             => 'Our atelier in Lyon employs six master embroiderers who have been working in the craft for a combined ninety-two years. Each botanical motif on this piece was placed by hand. It takes four hours per hoodie. We make twenty per month.',
                'rating'            => 5.0,
                'review_count'      => 14,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 30,
            ],
            [
                'name'              => 'Azure Long Sleeve – Sky Blue',
                'slug'              => Str::slug('Azure Long Sleeve – Sky Blue'),
                'description'       => 'Each piece is hand-dyed in small batches, meaning each one is uniquely yours. No two are identical.',
                'price'             => 445,
                'collection'        => 'limited-edition',
                'primary_color'     => 'Sky Blue',
                'colors'            => [['name' => 'Sky Blue', 'hex' => '#87CEEB', 'label' => 'Sky Blue']],
                'sizes'             => ['XS', 'S', 'M', 'L'],
                'images'            => ['/images/limited-edition/azure-long-sleeve-sky-blue.jpg'],
                'fabric_details'    => '100% Organic Cotton. Hand-dyed with natural plant-based pigments. Variation is intentional.',
                'care_instructions' => 'Hand wash cold only. Do not machine wash. Colour will deepen over time.',
                'story'             => 'We worked with a natural dye specialist for eight months to develop our Earth colorway. The pigments come from walnut shells, clay, and iron bark. Each piece absorbs the dye differently — your hoodie is a one-off.',
                'rating'            => 4.9,
                'review_count'      => 18,
                'in_stock'          => true,
                'is_new'            => false,
                'is_best_seller'    => false,
                'featured'          => false,
                'active'            => true,
                'sort_order'        => 31,
            ],
        ];
    }
}
